customauth/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from customauth.views import MyLoginView, MyRegisterView

app_name = "customauth"

urlpatterns = [
    # path("login/", HomeView.as_view(), name="login"),
    # path("logout/", LogOutView.as_view(), name="logout"),
    # path("register/", RegisterView.as_view(), name="register"),
    path("todo/login/", MyLoginView.as_view(), name="mylogin"),
    path('todo/logout/', LogoutView.as_view(next_page='customauth:mylogin'), name='mylogout'),
    path('todo/register/', MyRegisterView.as_view(), name='myregister'),
]

demo/urls.py
from django.urls import path

from demo.views import HomeView, CreateView, EditView, DeleteView

app_name = "demo"

urlpatterns = [
    path("home/", HomeView.as_view(), name="home"),
    path("create/", CreateView.as_view(), name="create"),
    path("edit/<int:pk>", EditView.as_view(), name="edit"),
    path("delete/<int:pk>", DeleteView.as_view(), name="delete")
]

drfauth/urls.py
from django.urls import path

from drfauth.views import RegisterView, LoginTestView

app_name = "drfauth"

urlpatterns = [
    path("register/", RegisterView.as_view(), name="register"),
    path("login/", LoginTestView.as_view(), name="login"),
]

jwtauth/urls.py
from django.urls import path
from rest_framework import routers

from jwtauth.views import LoginView, RefreshView, MyTokenVerifyView, RegisterViewSet, UserViewSet, UserTestViewSet

app_name = "jwtauth"

urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path("refresh/", RefreshView.as_view(), name="logout"),
    path('verify/', MyTokenVerifyView.as_view(), name='verify'),
    path("register/", RegisterViewSet.as_view(actions={"post": "create"}), name="register")
]

router = routers.DefaultRouter()
router.register(viewset=UserViewSet, prefix="user_info")
router.register(viewset=UserTestViewSet, prefix="user_test")

urlpatterns += router.urls

permissionTest/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, re_path
from django.urls import path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

urlpatterns = [
    path('admin/', admin.site.urls),
    # path("inner/", include("django.contrib.auth.urls")),
    path("account/", include("customauth.urls", namespace="myauth")),
    # path("demo/", include("demo.urls", namespace="mydemo")),
    # path("todo/", include("todoapp.urls", namespace="todo")),
    # path("drf/", include("drfauth.urls", namespace="mydrf")),
    # path("knox/", include("knoxauth.urls", namespace="authknox")),
    path("jwt/", include("jwtauth.urls", namespace="authjwt")),
]

schema_view = get_schema_view(
    info=openapi.Info(
        title="Snippets API",
        default_version='v1',
        description="Test description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="date20150619@icloud.com"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=[permissions.AllowAny],
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    urlpatterns += [
        re_path(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
        re_path(r'^swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
        re_path(r'^redoc/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
    ]

todoapp/urls.py
from django.urls import path

from todoapp.views import HomeView, TaskList, TaskDetail, TaskCreate, TaskUpdate, TaskDelete, MyProfile

app_name = "todoapp"

urlpatterns = [
    path("home/", HomeView.as_view(), name="home"),
    path("list/", TaskList.as_view(), name="tasks"),
    path('list/<int:pk>/', TaskDetail.as_view(), name='task'),
    path('list/create/', TaskCreate.as_view(), name='create'),
    path('list/update/<int:pk>/', TaskUpdate.as_view(), name='update'),
    path('list/delete/<int:pk>/', TaskDelete.as_view(), name='delete'),
    path('user/profile/', MyProfile.as_view(), name="profile")
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
    <title>Todo List</title>
</head>

<body>
<header class="header">
    <div class="container">
        <a href="{% url 'todoapp:home' %}" class="logo">Todo</a>
        <nav class="nav">
            <a href="{% url 'todoapp:home' %}"><i class="bi bi-house-fill"></i> Home</a>
            {% if request.user.is_authenticated %}
                <a href="{% url 'todoapp:tasks' %}"><i class="bi bi-list-task"></i> My Tasks</a>
                <a href="{% url 'todoapp:create' %}"><i class="bi bi-plus-circle"></i> Create Task</a>
                <a href="{% url 'todoapp:profile' %}">Hi {{ request.user | title }}</a>
                <a href="{% url 'customauth:mylogout' %}" class="btn btn-outline">Logout</a>
            {% else %}
                <a href="{% url 'customauth:mylogin' %}" class="btn btn-outline">Login</a>
                <a href="{% url 'customauth:myregister' %}" class="btn btn-primary">Join Now</a>
            {% endif %}
        </nav>
    </div>
</header>
<main>
    <div class="container">
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }}">
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}
        {% block content %}
        {% endblock %}
    </div>
</main>
<footer class="footer">
    <div class="container">
        <p>© Copyright {% now "Y" %} by <a href="https://github.com/jiubuchihuluobo">Jiubuchihuluobo</a></p>
    </div>
</footer>
</body>

</html>

templates/demo_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <link rel="stylesheet" href="{% static 'css/demo_style.css' %}"/>
    {#    <script src="{% static 'js/demo.js' %}" defer></script>#}
    <title>My Site</title>
</head>
<body>
<header>
    <a href="{% url 'demo:home' %}">Home</a>
    {% if request.user.is_authenticated %}
        <span>Hi {{ request.user.username | title }}</span>
        <a href="{% url 'myauth:logout' %}">Logout</a>
        <a href="{% url 'demo:create' %}">Create</a>
    {% else %}
        <a href="{% url 'myauth:login' %}">Login</a>
        <a href="{% url 'myauth:register' %}">Register</a>
    {% endif %}
</header>
<main>
    {% if messages %}
        <div class="messages">
            {% for message in messages %}
                <div class="alert {% if message.tags %}alert-{{ message.tags }}"{% endif %}>
                    {{ message }}
                </div>
            {% endfor %}
        </div>
    {% endif %}
    {% block content %}
    {% endblock %}
</main>
</body>
</html>