customauth/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from customauth.views import MyLoginView, MyRegisterView

app_name = "customauth"

urlpatterns = [
    # path("login/", HomeView.as_view(), name="login"),
    # path("logout/", LogOutView.as_view(), name="logout"),
    # path("register/", RegisterView.as_view(), name="register"),
    path("todo/login/", MyLoginView.as_view(), name="mylogin"),
    path('todo/logout/', LogoutView.as_view(next_page='customauth:mylogin'), name='mylogout'),
    path('todo/register/', MyRegisterView.as_view(), name='myregister'),
]

demo/urls.py
from django.urls import path

from demo.views import HomeView, CreateView, EditView, DeleteView

app_name = "demo"

urlpatterns = [
    path("home/", HomeView.as_view(), name="home"),
    path("create/", CreateView.as_view(), name="create"),
    path("edit/<int:pk>", EditView.as_view(), name="edit"),
    path("delete/<int:pk>", DeleteView.as_view(), name="delete")
]

permissionTest/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, re_path
from django.urls import path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

urlpatterns = [
    path('admin/', admin.site.urls),
    # path("inner/", include("django.contrib.auth.urls")),
    path("account/", include("customauth.urls", namespace="myauth")),
    # path("demo/", include("demo.urls", namespace="mydemo")),
    # path("todo/", include("todoapp.urls", namespace="todo")),
    # path("drf/", include("drfauth.urls", namespace="mydrf")),
    # path("knox/", include("knoxauth.urls", namespace="authknox")),
    path("jwt/", include("jwtauth.urls", namespace="authjwt")),
]

schema_view = get_schema_view(
    info=openapi.Info(
        title="Snippets API",
        default_version='v1',
        description="Test description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="date20150619@icloud.com"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=[permissions.AllowAny],
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    urlpatterns += [
        re_path(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
        re_path(r'^swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
        re_path(r'^redoc/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
    ]

todoapp/urls.py
from django.urls import path

from todoapp.views import HomeView, TaskList, TaskDetail, TaskCreate, TaskUpdate, TaskDelete, MyProfile

app_name = "todoapp"

urlpatterns = [
    path("home/", HomeView.as_view(), name="home"),
    path("list/", TaskList.as_view(), name="tasks"),
    path('list/<int:pk>/', TaskDetail.as_view(), name='task'),
    path('list/create/', TaskCreate.as_view(), name='create'),
    path('list/update/<int:pk>/', TaskUpdate.as_view(), name='update'),
    path('list/delete/<int:pk>/', TaskDelete.as_view(), name='delete'),
    path('user/profile/', MyProfile.as_view(), name="profile")
]

todoapp/models.py
import os

from PIL import Image
from django.db import models

from customauth.models import User


class Task(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField(null=True, blank=True)
    completed = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['completed']


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(default='avatar.jpg', upload_to='profile_avatars')

    def __str__(self):
        return f'{self.user.username} Profile'

    def save(self, *args, **kwargs):
        self.__class__.objects.filter(user__exact=self.user).delete()
        super().save(*args, **kwargs)
        if os.path.isfile(self.avatar.path):
            img = Image.open(self.avatar.path)
            if img.height > 300 or img.width > 300 or img.height < 300 or img.width < 300:
                output_size = (300, 300)
                # 创建缩略图
                img.thumbnail(output_size)
                img.save(self.avatar.path)

todoapp/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from todoapp.models import Task
from todoapp.serializers import UserUpdateForm, ProfileUpdateForm


class HomeView(View):
    def get(self, request):
        return render(request, "todoapp/home.html")


class TaskList(LoginRequiredMixin, ListView):
    model = Task
    context_object_name = 'tasks'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tasks'] = context['tasks'].filter(user=self.request.user)
        return context


class TaskDetail(LoginRequiredMixin, DetailView):
    model = Task
    context_object_name = 'task'

    def get_queryset(self):
        base_qs = super(TaskDetail, self).get_queryset()
        return base_qs.filter(user=self.request.user)


class TaskCreate(LoginRequiredMixin, CreateView):
    # 指定要创建对象的类
    model = Task
    # 指定表单上显示的字段
    fields = ['title', 'description', 'completed']
    # 是任务成功创建后Django将重定向到的目标URL
    success_url = reverse_lazy('todoapp:tasks')

    def form_valid(self, form):
        form.instance.user = self.request.user
        messages.success(self.request, "The task was created successfully.")
        # 如果验证成功保存并重定向到success_url
        return super(TaskCreate, self).form_valid(form)


class TaskUpdate(LoginRequiredMixin, UpdateView):
    model = Task
    fields = ['title', 'description', 'completed']
    success_url = reverse_lazy('todoapp:tasks')
    # 默认与CreateView公用一个视图，可以不设置
    template_name = "todoapp/task_form.html"

    def form_valid(self, form):
        messages.success(self.request, "The task was updated successfully.")
        return super(TaskUpdate, self).form_valid(form)

    def get_queryset(self):
        base_qs = super(TaskUpdate, self).get_queryset()
        return base_qs.filter(user=self.request.user)


class TaskDelete(LoginRequiredMixin, DeleteView):
    model = Task
    context_object_name = 'task'
    success_url = reverse_lazy('todoapp:tasks')

    def get_queryset(self):
        base_qs = super(TaskDelete, self).get_queryset()
        return base_qs.filter(user=self.request.user)


class MyProfile(LoginRequiredMixin, View):
    def get(self, request):
        user_form = UserUpdateForm(instance=request.user)
        profile_form = ProfileUpdateForm(instance=request.user.profile)
        context = {
            'user_form': user_form,
            'profile_form': profile_form
        }
        return render(request, 'todoapp/profile.html', context)

    def post(self, request):
        user_form = UserUpdateForm(data=request.POST, instance=request.user)
        profile_form = ProfileUpdateForm(data=request.POST, files=request.FILES, instance=request.user.profile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, 'Your profile has been updated successfully')
            return redirect('todoapp:profile')
        else:
            context = {
                'user_form': user_form,
                'profile_form': profile_form
            }
            messages.error(request, 'Error updating you profile')
            return render(request, 'todoapp/profile.html', context)

templates/todoapp/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <section class="feature">
        <div class="feature-content">
            <h1>Todo</h1>
            <p>Todo helps you more focus, either work or play.</p>
            <a class="btn btn-primary cta" href="{% url "customauth:myregister" %}">Get Started</a>
        </div>
        <img src="{% static 'images/feature.jpg' %}" alt="" class="feature-image">
    </section>
{% endblock %}

templates/todoapp/profile.html
{% extends 'base.html' %}

{% block content %}
    <div class="center">
        <form method="POST" enctype="multipart/form-data" class="card">
            {% csrf_token %}
            {% if user.profile %}
                <img src="{{ user.profile.avatar.url }}" alt="{{ user.username }}" class="avatar"/>
            {% endif %}
            <h2 class="text-center">{{ user.username | title }}</h2>
            <p class="text-center"><a href="mailto:{{ user.email }}">{{ user.email }}</a></p>
            <hr>
            <label for="email">Email Address:</label>
            <input type="email" id="email" name="email" value="{{ user.email }}"/>
            <label for="avatar">Avatar:</label>
            <input type="file" name="avatar" id="avatar">
            <button type="submit" class="btn btn-primary full-width">Update Profile</button>
        </form>
    </div>
{% endblock %}

templates/todoapp/task_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
    <div class="center">
        <form method="post" class="card">
            {% csrf_token %}
            <h2>Delete Task</h2>
            <p>Are you sure that you want to delete "{{ task }}"?</p>
            <p class="form-buttons">
                <input type="submit" class="btn btn-primary" value="Delete">
                <a href="{% url 'todoapp:tasks' %}" class="btn btn-outline">Cancel</a>
            </p>
        </form>
    </div>
{% endblock %}

templates/todoapp/task_detail.html
{% extends 'base.html' %}

{% block content %}
    <article class="task">
        <header>
            <h2>{{ task.title }}</h2>
            <span class="badge {% if task.completed %}badge-completed{% else %}badge-pending{% endif %}">
			{% if task.completed %} Completed {% else %} Pending {% endif %}
		</span>
        </header>
        <p>{{ task.description }}</p>
    </article>

{% endblock %}

templates/todoapp/task_form.html
{% extends 'base.html' %}

{% block content %}
    <div class="center">
        <form method="post" novalidate class="card">
            {% csrf_token %}
            <h2>{% if task %}Update Task{% endif %}Create Task</h2>
            {% for field in form %}
                {% if field.name == 'completed' %}
                    <p>
                        {{ field.label_tag }}
                        {{ field }}
                    </p>
                    {% if field.errors %}
                        <small class="error">{{ field.errors|striptags }}</small>
                    {% endif %}
                {% else %}
                    {{ field.label_tag }}
                    {{ field }}
                    {% if field.errors %}
                        <small class="error">{{ field.errors|striptags }}</small>
                    {% endif %}
                {% endif %}
            {% endfor %}

            <div class="form-buttons">
                <input type="submit" value="Save" class="btn btn-primary"/>
                <a href="{% url 'todoapp:tasks' %}" class="btn btn-outline">Cancel</a>
            </div>
        </form>
    </div>
{% endblock %}

templates/todoapp/task_list.html
{% extends 'base.html' %}

{% block content %}
    <div class="center">
        <h2>My Todo List</h2>
        {% if tasks %}
            <ul class="tasks">
            {% for task in tasks %}
                <li>
                    <a href="{% url "todoapp:task" task.id %}" class="{% if task.completed %}completed{% endif %}">{{ task.title }}</a>
                    <div class="task-controls">
                        <a href="{% url "todoapp:delete" task.id %}"><i class="bi bi-trash"></i> </a>
                        <a href="{% url "todoapp:update" task.id %}"><i class="bi bi-pencil-square"></i></a>
                    </div>
                </li>
            {% endfor %}
        {% else %}
            <p>🎉 Yay, you have no pending tasks!</p>
        {% endif %}
        </ul>
    </div>
{% endblock %}